webapp/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.http import request
from myhairdressing.forms import UploadForm,RegisterUserForm
from myhairdressing import views
from myhairdressing.views import *
from django.views.generic import DetailView, ListView
from django.contrib.auth.models import User


urlpatterns = (
    url(r'^admin/', admin.site.urls),
    url(r'^$', mainpage, name='Home'),
    url(r'^login/$', 'django.contrib.auth.views.login', kwargs={'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', kwargs={'next_page': '/'}),
    url(r'^register/$', views.register, name='registre'),
    url(r'^citation/create/$', views.CreateCitation, name='citation_create'),
    url(r'^citation/delete/$', views.DeleteCitation, name='citation_delete'),

    # Hairdressings

    url(r'^hairdressing/$',
        ListView.as_view(
            queryset=Hairdressing.objects.all(),
            context_object_name='HairdressingList',
            template_name='hairdressinglist.html'),
        name='hairdressingList'),

    # Hairdressing details
    url(r'^hairdressing/(?P<pk>\d+)/$',
        HairdressingDetail.as_view(),
        name='hairdressing_detail'),

    # User Citation
    url(r'^citations/$',
        ListView.as_view(
            queryset=Citation.objects.all(),
            context_object_name='CitationsList',
            template_name='citations.html', ),
        name='Citations'),

    url(
        r'thanks/(?P<username>[\w]+)/$',
        views.thanks_view,
        name='registration.thanks'
    ),
)

myhairdressing/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.utils.safestring import mark_safe

# Create your models here.


class Hairdressing(models.Model):

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150)
    street = models.CharField(max_length=150)
    number = models.CharField(max_length=6)
    zipcode = models.CharField(max_length=6)
    city= models.CharField(max_length=50)
    phone = models.CharField(max_length=12)
    description = models.TextField(max_length=4000)
    schedule_hairdressing = models.CharField(max_length=70)
    image = models.FileField(upload_to='myhairdressing/static/img')


    def __str__(self):
        return self.name


class Schedule(models.Model):

    id = models.AutoField(primary_key=True)
    DAY_CHOICES = ((1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'))
    day = models.PositiveSmallIntegerField('Dia', blank=False, default=1, choices=DAY_CHOICES)
    HOUR_CHOICES = ((9, '09:00h'),(10, '10:00h'),(11, '11:00h'),(12, '12:00h'),(13, '13:00h'),(14, '14:00h'),(15, '15:00h'),
                    (16, '16:00h'),(17, '17:00h'),(18, '18:00h'),(19, '19:00h'),(20, '20:00h'),)
    hour = models.PositiveSmallIntegerField('Hora', blank=False, default=1, choices=HOUR_CHOICES)
    schedule_hairdressing = models.ForeignKey(Hairdressing, related_name='schedule')

class Citation(models.Model):
    id = models.AutoField(primary_key=True)
    id_user = models.ForeignKey(User,related_name='citation')
    id_schedule = models.ForeignKey(Schedule, related_name='citation')

    def __str__(self):
        return 'Cita' + str(self.id)

myhairdressing/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UploadForm(forms.Form):
    image = forms.ImageField(
        label='Selecciona una imagen'
    )

class RegisterUserForm(forms.Form):

    username = forms.CharField(min_length=5)
    email = forms.EmailField()
    password = forms.CharField(min_length=5, widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    def clean_username(self):

        username = self.cleaned_data['username']
        if User.objects.filter(username=username):
            raise forms.ValidationError('Nombre de usuario ya registrado.')
        return username

    def clean_email(self):

        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError('Ya existe un email igual en la db.')
        return email

    def clean_password2(self):

        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']
        if password != password2:
            raise forms.ValidationError('Las contrasenas no coinciden.')
        return password2

myhairdressing/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, HttpResponseRedirect
from myhairdressing.models import Hairdressing,Citation,Schedule
from django.template.loader import get_template
from django.template import Context
from django.http import HttpResponse
from django.views.generic import DetailView
from django.contrib.auth.models import User
from django.shortcuts import redirect
from myhairdressing.forms import *

# Create your views here.

def mainpage(request):
    template = get_template("index.html")
    variables = Context({
        'user' : request.user
    })
    output = template.render(variables)
    return HttpResponse(output)

class HairdressingDetail(DetailView):
    model = Hairdressing
    template_name = 'hairdressing-detail.html'
    
    def get_context_data(self, **kwargs):
        context = super(HairdressingDetail, self).get_context_data(**kwargs)
        return context


class Citations(DetailView):
    model = Citation
    template_name = 'citations.html'

    def get_context_data(self, **kwargs):
        context = super(Citations,self).get_context_data(**kwargs)
        return context


def CreateCitation(request):
    u = request.POST.get('user')
    if (u == 'AnonymousUser'):
        return redirect('/login?id=1')
    else:
        us = User.objects.get(username=u)

        s = request.POST.get('schedule')
        sc = Schedule.objects.get(pk=s)

        c = Citation(id_user=us, id_schedule=sc)
        c.save()
        return redirect('/citations')


def DeleteCitation(request):
    id_citation = request.POST.get('id_citation')
    citation = Citation.objects.get(id=id_citation)
    citation.delete()
    return redirect('/citations')


def upload_file(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            newimg = Hairdressing(filename = request.POST['filename'],docfile = request.FILES['imgfile'])
            newimg.save(form)
            return redirect("uploads")


def register(request):
    if request.method == 'POST':

        form = RegisterUserForm(request.POST, request.FILES)

        if form.is_valid():

            cleaned_data = form.cleaned_data
            username = cleaned_data.get('username')
            password = cleaned_data.get('password')
            email = cleaned_data.get('email')

            user_model = User.objects.create_user(username=username, password=password)

            user_model.email = email

            user_model.save()

            return redirect(reverse('registration.thanks', kwargs={'username': username}))
    else:

        form = RegisterUserForm()

    context = {'form': form}

    return render(request, 'registration/register.html', context)


def thanks_view(request, username):
    return render(request, 'registration/thanks.html', {'username': username})

myhairdressing/templates/citations.html
{% extends "index.html" %}
{% block content %}
<h2>
    Mis Citas:
</h2>
    {% for citation in CitationsList %}
        {% if citation.id_user == user %}
        <div class="citation">
            <b>Peluquería: </b> {{ citation.id_schedule.hairdressing.name }} <br />
            <b>Dia: </b> {{ citation.id_schedule.get_day_display }} <br />
            <b>Hora: </b> {{ citation.id_schedule.get_hour_display }}
        <div>
            <form action="{% url 'citation_delete' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="id_citation" value="{{ citation.id }}">
                <input type="submit" value="Eliminar Cita">
            </form>
        </div>
        </div>
        {% endif %}
    {% endfor %}
{% endblock	%}

myhairdressing/templates/hairdressing-detail.html
{% extends "index.html" %}
{% block content %}
<h1>
	{{adminhairdressing.name}}

</h1>
<h2>Datos de la Peluquería:</h2>
<div style="height:210px;font-family: Symbol; font-size: 14px">
<img src="/{{ hairdressing.image }}" style="height:200px;float:left;padding-right:30px"/>
<ul style=" line-height: 40px; list-style: none">
	<li>Nombre: {{ hairdressing.name }}</li>
    <li>Dirección: {{ hairdressing.street }}, {{ hairdressing.number }}</li>
    <li>Ciudad: {{ hairdressing.city }}</li>
    <li>Teléfono: {{ hairdressing.phone }}</li>
    <li>Horario: {{ hairdressing.schedule_hairdressing }}</li>

</ul>

</div>

<br />

<span style="font-size: 14px"><span style="color: #990000; font-weight: bold;">Acerca de nosotros</span> <br /><br />{{ hairdressing.description }}</span>

<br /> <br />
<span style="font-size: 14px; font-weight: bold">Horario disponible para tu cita:</span>
<form style="margin-top:20px;" action="{% url 'citation_create' %}" method="POST">
{% csrf_token %}
{% for schedule in hairdressing.schedule.all %}
    <input checked type="radio" name="schedule" value="{{ schedule.id }}">{{ schedule.get_day_display }} {{ schedule.get_hour_display }} <br />
{% endfor %}
<br /><br />
<input type="hidden" name="user" value="{{ user }}">
<input class="button" type="submit" value="Pedir Cita">
</form>

<a style="float:right; font-size: 16px; text-decoration: underline" href="javascript:window.history.back()">Volver</a>

{% endblock %}

myhairdressing/templates/hairdressinglist.html
{% extends "index.html" %}
{% block content %}

<h2>
    Peluquerias:
</h2>
    {% for hairdressings in HairdressingList %}
        <div style="height: 160px;;">
            <div style="float:left;heigth: 150px;">
                <img src="/{{ hairdressings.image }} " style="width: 150px;padding-right:50px;">
            </div>
            <div style="margin-left:180px;font-size:16px;padding-top:60px;">
            <a href="{{ hairdressings.id }}">
                {{ hairdressings.name }}
            </a>
            </div>
        </div>
    {% empty %}No hay peluquerías asociadas.
    {% endfor %}
{% endblock	%}

myhairdressing/templates/index.html
<!DOCTYPE html>
<html lang="es" xmlns="http://www.w3.org/1999/html">
<head>
    {% load static %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">

    <meta charset="UTF-8">
    <title> Hairdressing Web</title>
</head>
<body>
	<div id="header">
		<h1><a href="/">Peluquerias Online</a> </h1>

    <div id="header-right">
            {% if user.username %} Bienvenido {{ user.username }}! | <a href="/logout">Desconectar</a> {% else %} <input class="button" type="button" value="Acceder" onclick="location.href='/login';"/>{% endif %}
    </div>
	</div>

    	<div id="content">
		<div id="sidebar">
			<ul>
            <li><a href="/">Inicio</a></li>
            <li><a href="/hairdressing">Listar Peluquerias</a></li>
      </ul>
      {% if user.username %}
      <div class="menuItem">Menú Usuario</div>
      <ul>
             <li><a href="/citations">Ver mis Citas</a></li>
      </ul>
      {% endif %}

      {% if user.is_superuser %}

      <div class="menuItem">Menú Administrador</div>
      <ul>
            <li><a href="/hairdressing">Modificar Peluquerías</a></li>
      </ul>
      {% endif %}

		</div>

		<div id="main-content">
            {% block content %}
                <h2>RESERVA CITAS DE BELLEZA Y PELUQUERIA</h2>
                <div style="width: auto; height: 630px; background-position:bottom ;background-image: url('{% static 'img/pelu.jpg' %}'); padding-top: 10px">

                    <div style="padding: 20px; margin-left: 10px; width: 450px; background-color: white; filter: alpha(opacity=60); -moz-opacity: 0.6; opacity: 0.6;">
                    Te proponemos la manera más rápida y cómoda para reservar un servicio sin que te muevas ... Peluquería innovadora donde arte, diseño y estilo se fusionan creando nuevas tendencias.<br>
                    <br> Escoge la peluqueria que más se adapte a ti.<a href="/hairdressing"> <strong><u>AQUI</u></strong></a></br>
                    </div>
                </div>

                <br><br/>
                    <b>Fecha:</b> 17/04/2016<br />
                    <b>Creadores:</b>
                    <ul>
                        <li>Jennifer Soliz</li>
                        <li>Jorge Belluscio</li>
                    </ul>

                    </ul>
            {% endblock	%}
		</div>

		<div class="clear"></div>
	</div>

</body>
</html>